project:
  type: website
  resources:
    - "data/*.csv"
    - "data/*.txt"

website:
  title: "CMU S&DS Data Repository"
  page-footer: "Maintained by the [Department of Statistics & Data Science](https://www.cmu.edu/dietrich/statistics-datascience/index.html), Carnegie Mellon University"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - by-method.qmd
      - submit-data.qmd
      - external-sources.qmd
  sidebar:
    contents: auto
    collapse-level: 1

format:
  html:
    theme:
      - cosmo
      - cmu.scss
    toc: true

execute:
  freeze: auto
