project:
  type: website
  resources:
    - "data/*.csv"
    - "data/*.txt"
  pre-render: prepare.lua
  post-render: build-csv.R

website:
  title: "CMU S&DS Data Repository"
  page-footer: "Maintained by the [Department of Statistics & Data Science](https://www.cmu.edu/dietrich/statistics-datascience/index.html), Carnegie Mellon University"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - by-method.qmd
      - submit-data.qmd
      - external-sources.qmd
  sidebar:
    contents: auto
    collapse-level: 1
  repo-url: https://github.com/cmustatistics/data-repository
  repo-actions: [edit, issue]

format:
  html:
    theme:
      - cosmo
      - cmu.scss
    toc: true
    df-print: paged

    include-in-header:
      - matomo-analytics.html

    filters:
      - metadata.lua

    template-partials:
      - _templates/title-metadata.html

execute:
  freeze: auto
