---
title: External Sources
---

Here are some good outside sources for finding datasets suitable for classes:

- [Data is Plural](https://www.data-is-plural.com/), a weekly newsletter of
  interesting public datasets.
- [SCORE Sports Data Repository](https://data.scorenetwork.org/), a collection
  of sports datasets for classroom use
- [Stanford Large Network Dataset Collection](https://snap.stanford.edu/data/)
- [Royal Society Open Science](https://royalsocietypublishing.org/journal/rsos),
  an open-access general science journal whose papers have Data Availability
  statements and often have public data
- [Scientific Data](https://www.nature.com/sdata/), a journal publishing
  descriptions of open datasets (often large and with unusual structure)
- [Data in Brief](https://www.sciencedirect.com/journal/data-in-brief), another
  journal publishing descriptions of open datasets
- [Open Case Studies](https://www.opencasestudies.org/), a collection of data
  analysis case studies showing analyses from conception to conclusion
- [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php),
  containing hundreds of datasets suitable for machine learning tasks
- [TidyTuesday](https://github.com/rfordatascience/tidytuesday), a project
  collecting datasets for weekly data wrangling and visualization events
