---
title: Submit a Dataset
---

Our overall goal is to provide a collection of useful, real-world datasets from
a variety of application areas that can be used as in-class examples, homework
assignments, or course projects. The repository can always use new datasets, so
we welcome submissions. Datasets should meet a few requirements:

- The data must be publicly shareable. There should not be any licensing
  restrictions that prevent us from sharing it, or any human subjects ethics
  concerns or other limitations. Look for datasets marked as being in the public
  domain or with licenses like the Creative Commons Attribution (CC-BY) license.
- The data should be in a standard, easy-to-use format, like CSV. If you have to
  clean the data from an original form, include the R script you used to clean
  it with your submission.
- There should be good motivation for interesting analyses of the data that
  would be appropriate for a course.


Once you've identified a dataset, you can download the data description template
file (TODO link). This template is a [Quarto](https://quarto.org/docs/guide/)
file; Quarto is much like R Markdown and is supported by recent versions of
RStudio.

The template asks for:

- Basic metadata, such as the statistical methods applicable to the data, a
  short title, and your name. (All submissions are credited with the name of the
  submitter.)
- A description of the problem. This should be sufficient to motivate the
  analysis and help students understand the setting.
- A description of the data and the variables. It should be clear what each row
  of data represents and what all variables mean. Units of measure should be
  included whenever possible.
- References to the original source. If the source is an academic paper and the
  data is deposited in a third-party repository (such as Zenodo, Figshare, or
  Dryad), include references to both the paper and the archived dataset. When
  available, include the DOIs of the references.

The template is meant to prevent a common problem with course datasets: they get
passed down from instructor to instructor, and eventually all information about
the original source is lost. The dataset may be presented to students without
context or important details (like units), and the instructor may not be able to
find the original data or references to answer questions about the data.

Once you've filled in the template, you can email the template file, the data,
and any cleaning scripts to TODO. Alternately, submit a pull request to our
repository on GitHub (TODO link).
