---
title: Spider nuptial gifts and fraud
author: Alex Reinhart
description: Male spiders give "gifts" of silk-wrapped food to female spiders to convince them to mate. Sometimes, they may cheat by gifting something other than food. Under what conditions do they cheat, and how much silk do they use to wrap fake gifts? Analyze an experiment on spiders in the lab.
date: June 15, 2017
categories:
  - ANOVA
  - linear regression
data:
  year: 2017
  files: spider-lab-gifts.csv
---

## Motivation

In the spider species *Pisaura mirabilis*, male spiders woo female spiders to
mate by giving them gifts: a piece of food (like a freshly captured insect)
wrapped in spider silk. If the gift is good, the female spider allows the male
to mate.

It turns out that sometimes male spiders cheat. Instead of wrapping food in
silk, they wrap something else, such as bits of a plant or an empty insect
exoskeleton they've already eaten from. This saves effort, though it runs the
risk of the female finding out and not accepting the gift; to avoid this, males
wrap the gifts in many extra layers of silk, so they can mate before the female
fully unwraps the gift and discovers what’s inside.

Researchers wanted to know why male spiders would cheat. Do they only cheat if
they are already starving and can’t spare the food for a gift, or do they cheat
opportunistically regardless of how much food they have to spare?

In the experiment presented here, male spiders kept in a laboratory were fed
different diets, and attributes of the spider and his gift were recorded to see
if there was a connection between the spider’s food and condition and the type
of gift he produced.

## Data

In each experiment, male spiders of roughly the same age were placed in small
boxes which previously held sexually receptive female spiders, to make them
think they should prepare a gift. The experimenters provided the males with a
live cricket nymph nearby, which they could presumably use as a gift; if the
male didn’t catch it within twenty minutes, or caught it but didn’t make a gift
with it, the experiment ended and was tried again a day later.

The weight of the prey before and after it was made into a gift was measured, to
see if the male ate some of it before wrapping it into a gift. The weight of the
silk used to wrap the prey was also recorded. (In a few cases, the prey and silk
couldn’t be separated, and weights are not recorded. You’ll have to exclude
these cases.)

### Data preview

```{r, echo=FALSE, results="asis"}
source("../preview_dataset.R")
preview_datasets()
```

### Variable descriptions

| Variable | Description |
|----|-------------|
| MALE ID |	Unique ID for each male spider |
| FOOD TREATMENT |	The diet the male was fed. HF: high food (two insects per week), LF: low food (one insect per week) |
| N TRIAL |	The number of the trial (e.g. 2 if it took two tries for the male to make a gift) |
| PREY WEIGHT BEFORE TRIAL (mg) |	The weight of the cricket nymph before the trial (milligrams) |
| Gift weight (mg) |	Weight of the gift produced (milligrams) |
| SILK WEIGHT (mg) |	Weight of the silk used to wrap the gift (milligrams) |
| PREY WEIGHT AFTER (gift - silk weight) |	Weight of the prey after it was used to make a gift (milligrams) |
| PREY WEIGHT LOSS |	Weight lost by prey (e.g. by the male spider eating some of it before making it into a gift) (milligrams) |
| MALE MASS BEFORE TRIAL (mg) |	Mass of the male spider (milligrams) |
| MALE CEPH WIDTH (mm) |	Width of the male spider's cephalothorax (millimeters) |
| MALE R BODY INDEX | See Questions, below |
| LATENCY TO WRAP (sec) |	Time elapsed between capturing the prey and starting to make a gift out of it (seconds) |
| MALE MASS AFTER TRIAL (mg) |	Mass of the male spider after making the gift (milligrams) |
| MALE WEIGHT difference (bef-after) |	Difference between male weight (before - after) |
| TOT WRAPPING DURATION (sec) |	Total time the male spent wrapping the gift (seconds)  |

## Questions

1. Does the male body weight (before the experiment) differ significantly
   between males fed the two different diets? What about their cephalothorax
   width?
2. If the prey lost weight, the male cheated and ate some of the prey before
   making a gift. Is the weight loss of the prey positively related to the mass
   of silk used to wrap it into a gift, as we’d expect if the male was hiding
   an inferior gift? Produce supporting graphs. Does the relationship depend on
   whether the male was fed the high or low food diet?

    (In three cases, the prey gained weight. According to the researchers, this
    is “most likely due to spiders’ injection of digestive fluids that serve for
    liquefying the prey during feeding”.)
3. Does the latency before wrapping the fit correlate with the weight loss of
   the gift, suggesting males waited longer to wrap inferior gifts (or waited
   too long and got tempted by the juicy cricket)?
4. Is there a difference in the weight loss of the prey between males fed the
   high food and low food diets? What about in the amount of silk used?
5. Regress the total time spent wrapping the gift against the mass of the gift.
   How many milligrams of silk can the male wrap per second?
6. According to the researchers, the `MALE R BODY INDEX` variable was calculated
   as “the residuals of a regression of body mass on body size (cephalothorax
   width)”. Perform the regression yourself and try to match your results
   against the researchers. Does it match?

## References

Ghislandi PG, Beyer M, Velado P, Tuni C (2017). Silk wrapping of nuptial gifts
aids cheating behaviour in male spiders. *Behavioral Ecology* 28 (3), 744-749.
<https://doi.org/10.1093/beheco/arx028>

Ghislandi P, Beyer M, Velado P, Tuni C (2017). Data from: Silk wrapping of
nuptial gifts aids cheating behaviour in male spiders. *Dryad Digital Repository*.
<https://doi.org/10.5061/dryad.kb1fh>
