---
title: Testosterone and diversity
author: Alex Reinhart
date: June 18, 2018
description: When students work on group projects, they work better when their groups are diverse. This study asked if that depends on the testosterone level of the group, and if high-testosterone groups benefit less from diversity.
categories:
  - linear regression
datayear: 2018
---

## Motivation

Some research has suggested that groups of people working on a task can do
better if the group is more diverse, since diverse group members can suggest
more creative ideas and make better decisions. At the same time, diverse groups
can have more conflict than less diverse groups, possibly eliminating those
benefits.

This dataset is from [a study](https://doi.org/10.1177/0956797617744282) that
attempted to understand these factors and how they relate to the testosterone
levels of members of the group. People with high levels of testosterone tend to
be competitive and may try to dominate their groups, leading to conflict, while
people with low testosterone may be more cooperative. So do groups with low
testosterone work better together, and benefit more from diversity, than those
with high testosterone?

The study involved 370 students working on their Master of Business
Administration degrees at Columbia Business School. The students were randomly
assigned to groups of three to six people, and their testosterone levels were
measured. The groups then did a week-long project where they pretended to run
blood-testing laboratories, with the goal of making their laboratories perform
better than those run by other groups in the class. Group members had to
collaborate with each other to decide on their strategy. At the end of the
project, the researchers recorded how well each group's laboratories did, how
much money they made, and so on.

The result, according to the study, was that

> The findings suggest that diversity is beneficial for performance, but only if
> group-level testosterone is low; diversity has a negative effect on
> performance if group-level testosterone is high.

## Data

The first data file contains individual data: the age, gender, and ethnicity of
each student, along with their testosterone and cortisol levels. The second file
reports the performance of the teams on their projects. There were 370 students
in 74 groups.

### Individual Data

| Variable | Description |
|----|-------------|
| ID 	| Participant ID number |
| team.id 	| ID number of the team this participant belonged to |
| Age 	| Age, in years |
| Gender 	| Gender (Male or Female) |
| Ethnicity 	| Ethnicity of the participant |
| Cortisol 	| Participant's cortisol levels, nMol/L |
| Testosterone 	| Participant's testosterone levels, pg/mL |
| log.cortisol 	| Natural logarithm of the participant's cortisol level |
| log.testosterone	| Natural logarithm of the participant's testosterone level |
| Country 	| Country of citizenship of the participant  |
: [hormone-diversity-individual.csv](../data/hormone-diversity-individual.csv)

### Team data

| Variable | Description |
|----|-------------|
| team.id 	| Team ID number |
| team.size 	| Number of people on the team |
| final.performance 	| The team's final performance score |
| time.of.day 	| The time of day the team's hormone sample was collected (hh.mm) |
| females 	| Number of females in the group |
| final.cash 	| Total cash earned by the team |
| final.contracts 	| Total number of contracts won by the team |
| final.reorders 	| Total number of reorders won by the team |
| final.rank 	| Team's final rank at the end of the project, relative to other teams in their class section |
| interim.performance	| Same as above, but measured at Day 5 of the study (missing for some teams) |
| interim.cash 	 | |
| interim.contracts 	 | |
| interim.reorders 	 | |
| interim.rank 	 | |
: [hormone-diversity-teams.csv](../data/hormone-diversity-teams.csv)

## Questions

1. The original paper measured the diversity of each group using something
   called "group faultline analysis", which looks at the group members' genders,
   countries of origin, and ethnicities to calculate a diversity score. The
   calculation is somewhat involved, so we'll make a simpler score. For each
   group, calculate the number of unique gender-ethnicity-country combinations
   (such as female-white-Russia or male-Indian-USA) among the group members, and
   store this with the other group information such as team size and
   performance. Also calculate the average testosterone level for each group.
2. Do exploratory data analysis to explore the composition of groups, the
   typical amount of diversity, and the typical amounts of testosterone. Note
   particularly that the data includes the logs of the cortisol and testosterone
   levels as well as the raw levels; does your EDA suggest you should use the
   logs or the raw values?
3. The data also includes participant ages. It's possible age is related to
   hormone levels, as is gender, and that both are related to final performance
   (perhaps older team members have more relevant experience, for example).
   Consider carefully whether you want to include these variables in the model,
   and how you should include them---average team member age? Gender
   proportion?
4. Build a model predicting group performance (`final.performance`) using the
   group's diversity score (be sure to control for the size of the group) and
   its average testosterone level. Is there an interaction between the two? Do
   your results resemble those presented by the original study?
5. The dataset also includes cortisol measurements. Cortisol is a hormone with
   many effects and roles in the body, but is commonly known as a "stress
   hormone" because its levels often increase because of sleep deprivation,
   intense exercise, and stress. Curiously, though cortisol is included in the
   data, it is not mentioned in the paper apart from an appendix. Include it in
   your analysis. Do stressed groups have better or worse performance? Does
   stress change the effect of diversity?

## References

M. Akinola, E. Page-Gould, P. H. Mehta, Z. Liu (2018). Hormone-Diversity Fit:
Collective Testosterone Moderates the Effect of Diversity on Group Performance.
*Psychological Science* 29 (6): 859-867.
<https://doi.org/10.1177/0956797617744282>

Data available from <https://osf.io/8eqtc/>
