---
title: Sugary drinks and portion limits
author: Alex Reinhart
date: June 14, 2017
description: Public health officials are interested in policies that would reduce consumption of sugary drinks. What policies work and what policies backfire? A factorial experiment.
categories:
  - ANOVA
  - logistic regression
data:
  files: sugary-drinks.csv
  year: 2017
---

## Motivation

Excess consumption of sugary drinks--soda, lemonade, sweet tea, and everything
in between--has been blamed for a variety of health problems, like diabetes and
obesity, which collectively cause billions of dollars of health costs each year.
Some governments are taking action to reduce consumption of sugary drinks; most
famously, the New York City Board of Health passed a regulation in 2012 banning
the sale of sugary drinks in containers larger than 16 ounces. Naturally there
was a backlash, and eventually a court case ruled the board [didn't have the
authority to make such a
rule](https://harvardlawreview.org/2015/03/new-york-statewide-coalition-of-hispanic-chambers-of-commerce-v-new-york-city-department-of-health-and-mental-hygiene/).

Regardless of New York's legal troubles, and setting aside the question of
whether sugary drinks are solely to blame for the health problems they
contribute to, we can ask the question "What kinds of regulations or serving
suggestions would make people drink smaller amounts?" Perhaps by limiting size,
changing serving methods, or with other small changes we could encourage people
to drink less without an outright ban.

Researchers conducted a series of experiments to try different strategies. The
dataset here is from one of those experiments.

Participants were invited to the lab for 90 minutes, during which they sat in a
cubicle and completed surveys and tasks for other unrelated psychological
studies. The experimenters provided them a bag of potato chips at the start to
make them thirsty, then offered them iced tea or lemonade during the experiment;
they were given a small amount of money at the start to use to buy the drinks,
and paid per drink.

There were two different manipulations. Participants were randomly assigned to
receive one of two sets of options:

1. A medium drink in a 16 ounce cup, or a large drink in a 24 ounce cup
   ("typical" condition), or
2. A medium drink in a 16 ounce cup, or a large drink served in two separate 12
   ounce cups (the "bundled" condition).

There were also two options for service, randomly assigned. Either

1. A research assistant walked to each cubicle, asking each participant what
   they'd like to drink ("waiter-served"), or
2. Participants walked to the back of the lab to buy their drinks
   ("self-served").

After the 90 minutes were up, the experimenters recorded how many ounces each
participant drank (by weighing their cups), how many calories they drank, what
kind of drinks they ordered, and a few demographic variables. Participants were
also asked what their drink options were, to make sure they understood them.

## Data

There were 623 total participants in this study, of whom 362 ordered a drink.
Each row represents one participant.

### Data preview

```{r, echo=FALSE, results="asis"}
source("../preview_dataset.R")
preview_datasets()
```

### Variable descriptions

| Variable | Description |
|----|-------------|
| id |	Unique ID for each study participant |
| IV_condition |	Experimental condition assigned. 1: waiter-served, typical. 2: waiter-served, bundled. 3: self-served, typical. 4: self-served, bundled |
| IV_service_dummy |	0 for waiter-served, 1 for self-served |
| IV_portion_dummy |	0 for typical drink portions, 1 for bundled drink portions |
| IV_service_dummy_by_IV_portion_dummy	|Interaction of the two previous dummy variables (1 if both are 1). |
| DV_order_at_all |	1 if the participant ordered any drinks at all |
| DV_order_large |	1 if they ordered the large size, 0 if they ordered medium. Left blank if they didn't order any drinks |
| DV_ounces_consumed |	Total number of ounces consumed by the participant |
| DV_calories_consumed |	Total number of calories consumed by the participant |
| flavor |	0: Snapple lemon tea, 1: Vitamin Water squeezed lemonade. Left blank if the participant did not order a drink. |
| sex |	1: male, 2: female |
| age | Age, in years |
| ethnicity |	1: African American, 2: American Indian or Alaskan Native, 3: Asian, 4: Caucasian, 5: Hispanic/Latino, 6: Pacific Islander, 7: Other or mixed |
| comprehension_check |	 |
| failed_comprehension_check |	Did the participant fail a test at the end to make sure they knew what their drink options were? 0: no, 1: yes  |

## Questions

1. Perform basic EDA. What fraction of people ordered drinks, and of those who
   did, what fraction ordered medium or large? Which type of drink was most
   popular? Does there seem to be any difference depending on their drink
   options or service style?

2. Build a model to predict whether each participant orders a large drink,
   depending on the portion (typical vs. bundled) and the type of service
   (waiter-served or self service). Consider including an interaction if
   necessary.

    Did the portion type or service type affect drink orders? In what way?

3. Participants didn't necessarily finish the drinks they ordered. Analyze the
   number of calories they consumed, depending on the portion type and type of
   service. Again, consider including an interaction if it seems necessary.

    The researchers hypothesized that bundling may reduce consumption, since
    having drinks in two separate cups makes it easier to realize how much
    you're drinking. Is there evidence to support this? Does it seem to matter
    whether participants had to give their order to an assistant or served
    themselves?

    Repeat your analysis, this time only including those who did not fail the
    comprehension check at the end, which checked that they correctly understood
    their drink options. Are the results consistent?

4. The experiment wasn't intended for this purpose, but we can conduct a purely
   exploratory analysis using this data to explore drink preferences. Of those
   participants who ordered a drink, how many favored Snapple and how many
   favored lemonade? Do preferences depend on sex, age, or ethnicity? Build a
   model to predict the flavor of drink a participant ordered. How accurate is
   it?

## References

Leslie K. John, Grant E. Donnelly, and Christina A. Roberto (2017).
Psychologically Informed Implementations of Sugary-Drink Portion Limits.
*Psychological Science* 28 (5) 620-629.
<https://doi.org/10.1177/0956797617692041>

Data available from the Open Science Framework, at <https://osf.io/93m8y>
